# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2f5ee1fd86019e2888b605bf1c05ab45a8907ba8a8ad66be4f1c300aadb6502f4468c8039f0036ff630f72176217ad67c4a99c83960577e398f82cf2134e86e

test:
  secret_key_base: adc7dd78f254cdebbac6606385654eb7ecdb767e9fc74e34b9105f881f6be3a2c3fbdfce0468a2d08147d2fb603056a21dcfcdf2aabbf4d11629da869c190671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
